### ISSUE TITLE
TerrariaUnified does not launch on Windows 11

### ISSUE THREAD

**Issue by fishiatee** [terraprisma/terraprisma#12]
Might make a bug report here since it's the only place where TU is released and I don't have a TCF account.

I randomly stumbled upon this project, seems cool so decided to install and try it myself.

Created a folder next to Terraria.exe (like tModLoader) and put all TU files there, tried to run the included Terraria.exe but nothing happened. Then I tried to overwrite my Terraria installation with TU files but still nothing. After all of that I decided to invoke `dotnet` manually and got this error (log is included below.). Nothing worked.

[log.txt](https://github.com/steviegt6/terraprisma/files/13327883/log.txt)

**Comment by steviegt6** [comment]
You're missing `rail_api.dll`, a partial mistake on my end. I should probably provide those natives as well for checking, but this means it failed to initialize Steam first. I provide Steam natives so that shouldn't have happened, do you have a Steam installation of Terraria?

**Comment by FishiaT** [comment]
No, I own Terraria on GOG.
Let me try installing Steam though.

**Comment by FishiaT** [comment]
Strangely enough, I couldn't find any information about Rail API anything on the internet.

**Comment by steviegt6** [comment]
Rail is what Terraria uses for WeGame; Chinese stuff.

**Comment by FishiaT** [comment]
Alright, got it to launch by passing `-none` as an argument.

**Comment by steviegt6** [comment]
Glad you found a fix; I'm going to reopen this as an issue for proper WeGame detection (or at least ample error handling).

**Comment by steviegt6** [comment]
Forgot to close this; fixed in https://github.com/terraprisma/unified/commit/8c24368495951800a453327e720e40361b3986de.
